## Importing and reading data from files

We don't usually create the arrays that we work with. We need to be able to import data present in another file to Numpy.

Numpy provides useful functions to load data from an external file and save it as well.

The main import methods are:

1. numpy.loadtxt()
2. numpy.genfromtext()

Use `np.loadtxt` when there is no missing value in the data.

In [14]:
import numpy as np

In [20]:
data = np.loadtxt('data.txt', delimiter="\t")
data

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     ,  2.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 7.     , 43.     , 39.62271],
       [ 8.     , 47.     , 34.95107],
       [ 9.     ,  2.     ,  9.38692],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894],
       [12.     , 24.     , 23.47974],
       [13.     , 61.     , 72.55357],
       [14.     , 85.     , 39.24693],
       [15.     , 63.     , 53.6279 ],
       [16.     ,  2.     , 16.72441],
       [17.     , 29.     , 37.25533],
       [18.     , 45.     , 18.78498],
       [19.     , 33.     , 19.8089 ],
       [20.     , 28.     , 46.03384],
       [21.     , 21.     , 23.7864 ],
       [22.     , 27.     , 44.42627],
       [23.     , 65.     , 34.94804],
       [24.     , 61.     , 53.49576],
       [25.     , 10.     , 25.98564]])

In [22]:
type(data)

numpy.ndarray

**But this function throws error when reading files with missing values**

In [27]:
data = np.loadtxt('data_miss.txt', delimiter="\t")
data

ValueError: could not convert string '' to float64 at row 8, column 3.

In such situation, use `np.genfromtxt()`. It fills in missing data with `nan`.

In [30]:
data = np.genfromtxt('data_miss.txt', delimiter="\t")
data

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     ,  2.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 7.     , 43.     , 39.62271],
       [ 8.     , 47.     , 34.95107],
       [ 9.     ,  2.     ,      nan],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894],
       [12.     , 24.     ,      inf],
       [13.     , 61.     , 72.55357],
       [14.     , 85.     , 39.24693],
       [15.     , 63.     , 53.6279 ],
       [16.     ,  2.     , 16.72441],
       [17.     , 29.     ,      nan],
       [18.     , 45.     , 18.78498],
       [19.     , 33.     , 19.8089 ],
       [20.     , 28.     , 46.03384],
       [21.     , 21.     , 23.7864 ],
       [22.     , 27.     , 44.42627],
       [23.     , 65.     , 34.94804],
       [24.     , 61.     , 53.49576],
       [25.     , 10.     , 25.98564]])

#### Loading data from csv files

Let's try loading a csv file with column names.

By default, it takes the dtype as `float`. In such cases, the text fields will convert to missing values.

In [35]:
data = np.genfromtxt('Mall_Customers.csv', delimiter=",")
data

array([[ nan,  nan,  nan,  nan,  nan],
       [  1.,  nan,  19.,  15.,  39.],
       [  2.,  nan,  21.,  15.,  81.],
       ...,
       [198.,  nan,  32., 126.,  74.],
       [199.,  nan,  32., 137.,  18.],
       [200.,  nan,  30., 137.,  83.]], shape=(201, 5))

In [39]:
data = np.genfromtxt('Mall_Customers.csv', 
                     delimiter=",", 
                     dtype='object',
                    skip_header=1)

In [41]:
data[0:5]

array([[b'1', b'Male', b'19', b'15', b'39'],
       [b'2', b'Male', b'21', b'15', b'81'],
       [b'3', b'Female', b'20', b'16', b'6'],
       [b'4', b'Female', b'23', b'16', b'77'],
       [b'5', b'Female', b'31', b'17', b'40']], dtype=object)

The problem with this is, the numbers are identified as bytes and not as numbers. So doing math is not easy.

In [46]:
# try dividing 4th col with 3rd col and we get error
data[:, 3] / data[:, 2]

TypeError: unsupported operand type(s) for /: 'bytes' and 'bytes'

#### Better solution to this problem

In [49]:
dt = np.dtype({'names': ["CustomerID", "Genre", "Age", "Annual_Income", "Spending_Score"],
               'formats': [np.int16, 'U16', np.int16, np.int16, np.int16]})

In [51]:
data = np.genfromtxt('Mall_Customers.csv', 
                     delimiter=",", 
                     dtype=dt,
                    skip_header=1)

In [55]:
data[0:5]

array([(1, 'Male', 19, 15, 39), (2, 'Male', 21, 15, 81),
       (3, 'Female', 20, 16,  6), (4, 'Female', 23, 16, 77),
       (5, 'Female', 31, 17, 40)],
      dtype=[('CustomerID', '<i2'), ('Genre', '<U16'), ('Age', '<i2'), ('Annual_Income', '<i2'), ('Spending_Score', '<i2')])

In [57]:
data.ndim

1

In [61]:
import pandas as pd

In [65]:
pd.DataFrame(data)

,CustomerID,Genre,Age,Annual_Income,Spending_Score
0,1,Male,19,15,39
1,2,Male,21,15,81
2,3,Female,20,16,6
3,4,Female,23,16,77
4,5,Female,31,17,40
...,...,...,...,...,...
195,196,Female,35,120,79
196,197,Female,45,126,28
197,198,Male,32,126,74
198,199,Male,32,137,18


#### Export the array

If it's a single array, save it in `.npy` format. If you have multiple arrays to save in same file, use `.npz` format.

In [77]:
# Single array
np.save('output.npy', data)

# Multiple arrays: arrays will be save with names "arr_0", "arr_1",..
np.savez('outputs.npz', data)

#### Load the data back from the saved numpy array

In [79]:
a = np.load('output.npy')

In [81]:
a

array([(  1, 'Male', 19,  15, 39), (  2, 'Male', 21,  15, 81),
       (  3, 'Female', 20,  16,  6), (  4, 'Female', 23,  16, 77),
       (  5, 'Female', 31,  17, 40), (  6, 'Female', 22,  17, 76),
       (  7, 'Female', 35,  18,  6), (  8, 'Female', 23,  18, 94),
       (  9, 'Male', 64,  19,  3), ( 10, 'Female', 30,  19, 72),
       ( 11, 'Male', 67,  19, 14), ( 12, 'Female', 35,  19, 99),
       ( 13, 'Female', 58,  20, 15), ( 14, 'Female', 24,  20, 77),
       ( 15, 'Male', 37,  20, 13), ( 16, 'Male', 22,  20, 79),
       ( 17, 'Female', 35,  21, 35), ( 18, 'Male', 20,  21, 66),
       ( 19, 'Male', 52,  23, 29), ( 20, 'Female', 35,  23, 98),
       ( 21, 'Male', 35,  24, 35), ( 22, 'Male', 25,  24, 73),
       ( 23, 'Female', 46,  25,  5), ( 24, 'Male', 31,  25, 73),
       ( 25, 'Female', 54,  28, 14), ( 26, 'Male', 29,  28, 82),
       ( 27, 'Female', 45,  28, 32), ( 28, 'Male', 35,  28, 61),
       ( 29, 'Female', 40,  29, 31), ( 30, 'Female', 23,  29, 87),
       ( 31, 'Male', 

# Business Problem Statements using Numpy

### The Ride-Sharing App (Urban Mobility Analytics)

You are a Data Scientist at a major ride-sharing company (like Uber or Lyft). The city operations team has given you a batch of ride data from a busy Friday night. They need deep insights into driver efficiency, surge pricing dynamics, and rider satisfaction to optimize the matching algorithm.

1.1 **Data Ingestion**: Load the data into a NumPy array.

In [186]:
data = np.genfromtxt('ride_data.csv', delimiter=',', skip_header=1)

ride_ids = data[:, 0]
driver_ids = data[:, 1]
distances = data[:, 2]
durations = data[:, 3]
fares = data[:, 4]
surges = data[:, 5]
d_ratings = data[:, 6]
r_ratings = data[:, 7]

**These are the columns in the data**

ride_id, driver_id, distance_miles, duration_minutes, fare_usd, surge_multiplier, driver_rating, rider_rating

- `ride_id` : The unique id given to every ride.
- `driver_id` : The unique driver id of each driver.
- `distance_miles` : Distance covered from origin to destination (in miles).
- `duration_minutes` : Duration of each ride in minutes.
- `fare_usd` : Total fare of the ride is US Dollars.
- `surge_multiplier` : surge pricing will activate for a ride during a certain event and the user will have to pay a higher amount. For example, if the surge multiplier is 1.2, then the `total fare will be normal ride fare * 1.2`.
- `driver_rating` : Rating given to the driver by the user.
- `rider_rating` : Rating given to rider by the driver for a trip

In [189]:
data

array([[  1. , 101. ,   5.2,  15. ,  18.5,   1. ,   4.9,   5. ],
       [  2. , 102. ,  12.5,  35. ,  45. ,   1.5,   4.7,   4.2],
       [  3. , 101. ,   2.1,   8. ,   9. ,   1. ,   4.9,   4.8],
       [  4. , 103. ,   8. ,  25. ,  32. ,   1.2,   4.5,   4.9],
       [  5. , 104. ,   1.5,  10. ,  12.5,   2. ,   5. ,   3.5],
       [  6. , 102. ,  15. ,  45. ,  60. ,   1. ,   4.7,   4.7],
       [  7. , 105. ,   3.3,  12. ,  14. ,   1. ,   4.2,   4.5],
       [  8. , 101. ,   4.5,  14. ,  16.5,   1. ,   4.9,   5. ],
       [  9. , 103. ,  10.2,  30. ,  38. ,   1.2,   4.5,   4.1],
       [ 10. , 104. ,   0.8,   5. ,   8. ,   1.5,   5. ,   5. ],
       [ 11. , 106. ,   6.7,  22. ,  24. ,   1. ,   4.8,   4.8],
       [ 12. , 102. ,  22.1,  55. ,  85. ,   1. ,   4.7,   4.9],
       [ 13. , 107. ,   3.1,  11. ,  15.5,   1.5,   3.9,   4. ],
       [ 14. , 101. ,   5. ,  15. ,  18. ,   1. ,   4.9,   4.5],
       [ 15. , 105. ,   1.2,   7. ,   7.5,   1. ,   4.2,   4.6],
       [ 16. , 106. , 130

2.1 **Gross Merchandise Value (GMV)**: Calculate the total fares collected.

2.2 **Platform Revenue**: The company takes a 25% commission. Calculate total platform revenue.

In [192]:
gmv = np.sum(fares)
platform_revenue = gmv * 0.25
print(f"Total GMV: ${gmv:.2f} | Platform Cut: ${platform_revenue:.2f}")

Total GMV: $503.50 | Platform Cut: $125.88


This means, for all rides in the data, company collected total fare of `$403.50`. And since they keep only 25% commission from it, their total revenue was `$100.88`.

The GMV is the sum of every single dollar paid by every single rider before the company and the driver gets their cut.

Imagine you build an app that connects local bakers with customers. A customer buys a `$100` wedding cake. You take a `$10` fee for connecting them, and the baker keeps $90.

- Your Revenue is $10.

- But the GMV of that transaction is $100.

**How and why it helps a company:**
In Big Tech (Uber, Airbnb, Amazon, eBay), GMV is the ultimate vanity metric for scale and market share. Investors look at GMV to see how much economic activity the platform is generating.

- If a ride-sharing app has a GMV of $1 Billion, it means they control a massive chunk of city transportation.

- `It also dictates their potential ceiling`: you cannot increase your revenue without either taking a bigger percentage cut (which angers drivers) or increasing the overall GMV.

---

3.1 **Average Speed**: Calculate the average speed (mph) for every ride to check for traffic anomalies.

3.2 **Speeding Flag**: Identify ride_ids where the average speed exceeded 65 mph.

In [203]:
speeds_mph = distances / (durations / 60)
speeding_rides = ride_ids[speeds_mph > 65]
print("\nSpeeds (mph):\n", np.round(speeds_mph, 1))
print("Speeding Ride IDs:", speeding_rides.astype(int))


Speeds (mph):
 [ 20.8  21.4  15.8  19.2   9.   20.   16.5  19.3  20.4   9.6  18.3  24.1
  16.9  20.   10.3 130. ]
Speeding Ride IDs: [16]


4.1 **Surge Impact Calculation**: How much extra money was generated purely because of surge multipliers?

In [199]:
base_fares = fares / surges
surge_extra_revenue = np.sum(fares - base_fares)
print(f"\nExtra Revenue from Surge: ${surge_extra_revenue:.2f}")


Extra Revenue from Surge: $57.42


Surge pricing is a dynamic pricing model. A Surge Multiplier is the exact number the base fare is multiplied by (e.g., 1.5x, 2x) during periods of high demand.

**Why it is implemented:**
Surge pricing exists to solve a simple supply-and-demand problem. When demand is much more than supply, the system breaks. Surge pricing does two things simultaneously:

- `Incentivizes or Encourages Supply of Drivers`: It alerts drivers ("There is a 2.0x surge in that area") prompting more drivers to log on or drive toward that the area of high demand.

- `Controls Demand`: It discourages riders who don't urgently need a ride. Someone might decide to wait 20 minutes or take the bus, freeing up the available cars for people who want it more urgently and are willing to pay the premium (like someone rushing to the airport).

5.1 **Driver Fleet Performance**: What is the median driver rating?

In [118]:
median_rating = np.median(d_ratings)
print(f"\nMedian Driver Rating: {median_rating}")


Median Driver Rating: 4.7


6.1 **Top Earner Identification**: Find the exact row index of the highest single fare.

In [122]:
max_fare_idx = np.argmax(fares)
print(f"\nHighest fare was ${fares[max_fare_idx]} on Ride ID {int(ride_ids[max_fare_idx])}")


Highest fare was $85.0 on Ride ID 12


7. **Short-Trip Ratio**: What percentage of rides were under 3 miles?

In [239]:
short_trips_pct = np.mean(distances < 3.0) * 100
print(f"\nShort Trips (< 3 miles): {short_trips_pct:.1f}%")


Short Trips (< 3 miles): 25.0%


8. **Rating Discrepancy**: Calculate the absolute difference between the driver's rating and the rider's rating for each trip.

In [128]:
rating_diff = np.abs(d_ratings - r_ratings)
print("\nAbsolute Rating Discrepancies:\n", np.round(rating_diff, 1))


Absolute Rating Discrepancies:
 [0.1 0.5 0.1 0.4 1.5 0.  0.3 0.1 0.4 0.  0.  0.2 0.1 0.4 0.4]


9. **High-Value Threshold**: Find the 90th percentile fare amount.

The `High-Value Threshold` is the dollar amount that separates the top 10% most expensive rides from the bottom 90% of normal rides.

If the 90th percentile is `$42.00`, it means `90%` of all rides cost less than `$42`, and only the top 10% cost more.

In [131]:
p90_fare = np.percentile(fares, 90)
print(f"\n90th Percentile Fare Threshold: ${p90_fare:.2f}")


90th Percentile Fare Threshold: $54.00


A ride might cross this threshold because it’s a very long distance (an airport drop-off), it happened during a massive 3.0x surge, or the rider booked a luxury SUV (Uber Black).

**Why Data Scientists calculate it:**

You calculate this threshold to segment your data and treat those "premium" trips differently.

- **For Operations**: You want to make sure your absolute best, 5-star drivers are the ones being dispatched to these high-value riders to ensure a flawless experience.

- **For Marketing**: If you know the threshold is `$42`, you can run a campaign: "Spend over `$45` on a ride and get a free coffee voucher."

- **For Anomaly Detection**: If a ride is way, way past this threshold (e.g., $400), a Data Scientist might flag it for review to ensure the GPS didn't glitch or the driver didn't intentionally take the rider in circles to rack up the bill.


10. **Efficiency Metric**: Calculate the dollars earned per minute for each ride.

In [134]:
dollars_per_minute = fares / durations
print("\nDollars earned per minute:\n", np.round(dollars_per_minute, 2))


Dollars earned per minute:
 [1.23 1.29 1.12 1.28 1.25 1.33 1.17 1.18 1.27 1.6  1.09 1.55 1.41 1.2
 1.07]


11. **Perfect Match Filter**: Find ride_ids where both driver and rider gave a 5.0 rating.

In [137]:
perfect_mask = (d_ratings == 5.0) & (r_ratings == 5.0)
print("\nPerfect Match Ride IDs:", ride_ids[perfect_mask].astype(int))


Perfect Match Ride IDs: [10]


12. **Driver Penalty**: Create an array of driver payouts (75% of fare). If the driver rating is below 4.0, deduct a flat $3 penalty using np.where.

In [143]:
standard_payout = fares * 0.75
adjusted_payout = np.where(d_ratings < 4.0, standard_payout - 3.00, standard_payout)
print("\nAdjusted Payouts (First 5):\n", np.round(adjusted_payout[:5], 2))


Adjusted Payouts (First 5):
 [13.88 33.75  6.75 24.    9.38]


13. **Cumulative Fares**: Calculate the running total (cumulative sum) of fares as the night progressed.

In [146]:
cum_fares = np.cumsum(fares)
print("\nRunning Total of Fares:\n", np.round(cum_fares, 2))


Running Total of Fares:
 [ 18.5  63.5  72.5 104.5 117.  177.  191.  207.5 245.5 253.5 277.5 362.5
 378.  396.  403.5]


14. **Busiest Driver**: Find the driver_id that completed the most rides in this dataset.

In [151]:
unique_drivers, counts = np.unique(driver_ids, return_counts=True)
busiest_driver = unique_drivers[np.argmax(counts)]
print(f"\nBusiest Driver ID: {int(busiest_driver)}")


Busiest Driver ID: 101


15. **Duration Sorting**: Get the list of ride_ids sorted from shortest duration to longest duration.

In [156]:
sorted_ride_ids = ride_ids[np.argsort(durations)]
print("\nRide IDs sorted by duration (fastest to longest):", sorted_ride_ids.astype(int))


Ride IDs sorted by duration (fastest to longest): [10 15  3  5 13  7  8  1 14 11  4  9  2  6 12]


On the surface it seems like such a basic thing to keep track of. But business wise it makes a lot of sense and help a company. How?

When you sort rides by duration, you are immediately identifying two highly problematic categories for the business: `the Micro-Trips (the shortest rides)` and the `Out-of-Position Trips (the longest rides)`.

**1. Analyzing "Micro-Trips" (The Shortest Durations)**
When you look at the top of your sorted list (rides taking 2 to 5 minutes), you are looking at trips that are often highly inefficient for cars.

- **The Driver Frustration Problem**: Imagine a driver spends 8 minutes fighting through city traffic just to pick up a passenger who only wants to go few kms (a 2-minute ride). The driver earns very little and feels like they wasted their time.

- **The Business Solution**: By identifying the volume of these micro-trips, the platform can make strategic decisions. They might implement a "Minimum Fare" to ensure drivers earn a fair amount for their time. Alternatively, if the data shows thousands of these 3-minute rides in a specific area, the company might deploy fleets of electric scooters or e-bikes there, prompting the user in the app: "A car is `$8` and takes 5 mins. A scooter is `$2` and takes 4 mins."

**2. Managing "Deadheading" (The Longest Durations)**
When you look at the very bottom of your sorted list (rides taking 45+ minutes), you are looking at rare outlier rides. They generate a lot of revenue, but they create a massive logistical headache.

- **The "Deadhead" Problem**: A 60-minute ride from the busy city center is great money. But once the driver drops the passenger off, they are stuck in a location where there is no demand. They have to drive 60 minutes back to the city empty. In the logistics world, driving empty is called "deadheading," and it means the driver is burning petrol and losing money.

- **The Business Solution**: By analyzing these long-duration rides, platforms developed features like the "Destination Filter." If a driver gets taken 60 minutes out of the city, the algorithm will specifically look for a passenger outside the city who wants to travel back towards the city, offering it to that specific driver so they get paid for their return trip. Platforms also sometimes add a "Long Trip Premium" fee to the rider to compensate the driver for the empty return journey.

Matrix Reshaping: The ML team needs the first 12 driver and rider ratings reshaped into a 3D tensor (2x2x6) for a specific neural network input.

In [159]:
ratings_subset = np.vstack((d_ratings[:12], r_ratings[:12]))
tensor_3d = ratings_subset.reshape(2, 2, 6)
print("\n3D Tensor Shape:", tensor_3d.shape)


3D Tensor Shape: (2, 2, 6)


In [247]:
ratings_subset

array([[4.9, 4.7, 4.9, 4.5, 5. , 4.7, 4.2, 4.9, 4.5, 5. , 4.8, 4.7],
       [5. , 4.2, 4.8, 4.9, 3.5, 4.7, 4.5, 5. , 4.1, 5. , 4.8, 4.9]])